### ISSUE TITLE
Problems with Cracked account!

### ISSUE THREAD

**Issue by qSox** [ad1tya2/AdiAuth#3]
As I wrote before, I noticed a problem with the entry of people with a non-premium account.When he tries to enter, he kick for the reason that he has to change his nickname, there is already one in the game.And the man enters for the first time in the server.Just to say that the server is not open yet and there is no way anyone could log in with his nickname or have a premium account logged into the server.If you can look and see what the problem is.There is no problem with premium players now this may have happened by accident I can't say but I don't want to take a risk when the server is running there are often such problems and people complain that they can't log in and they have to change their names!

**Comment by ad1tya2** [comment]
So this is the issue,
Basically what happens is that cracked players who have an username that is being used by a premium player, it won't allow you to log in,
For example if you use the name `Grian` in tlauncher and try to join then it will show that you can't join.
But if you try to join with the name `xgeudy6374` from tlauncher it will work without any issues since no premium player has an account with that name

**Comment by ad1tya2** [comment]
This will happen even if a premium person with that name has never joined the server

**Comment by qSox** [comment]
clearly do you have an idea when paying, similar to plugins that have had the same issue.

**Comment by ad1tya2** [comment]
I don't get what you are trying to say in this reply at all

**Comment by qSox** [comment]
Paid plugins that are similar to this plugin  work in the same way ?Or you don't know.

**Comment by ad1tya2** [comment]
Well the real mode in jpremium works like this, I don't know about others, fastlogin also works like this afaik

**Comment by qSox** [comment]
I understood well, I apologize then
